In [169]:
import pandas as pd

df_categoria_bronze = pd.read_parquet('../data/bronze/PS_Categoria.parquet')
df_cliente_bronze = pd.read_parquet('../data/bronze/PS_Cliente.parquet')
df_conta_pagamento_bronze = pd.read_parquet('../data/bronze/PS_Conta_Pagar.parquet')
df_conta_receber_bronze = pd.read_parquet('../data/bronze/PS_Conta_Receber.parquet')
df_meta_bronze = pd.read_parquet('../data/bronze/PS_Meta2025.parquet')
df_banco_central_bronze = pd.read_parquet('../data/bronze/bcb_cotacoes.parquet')

In [170]:
df_categoria_bronze.head()

  codigo_categoria                        nome_categoria tipo_categoria
0           1.1.01           VENDA DE PRODUTOS NACIONAIS        receita
1           1.1.02          VENDA DE PRODUTOS EXPORTAÇÃO        RECEITA
2           1.1.03       PRESTAÇÃO DE SERVIÇOS NACIONAIS        Receita
3           1.1.04  PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS        reCeita
4           1.1.05                RECEITA DE ASSINATURAS        REceita

In [171]:
print(df_categoria_bronze.info())
print(df_categoria_bronze.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo_categoria  34 non-null     object
 1   nome_categoria    34 non-null     object
 2   tipo_categoria    34 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes
None
codigo_categoria  nome_categoria                            tipo_categoria
3.1.06            ÁGUA E SANEAMENTO                         despesa           2
1.1.02            VENDA DE PRODUTOS EXPORTAÇÃO              RECEITA           1
1.1.01            VENDA DE PRODUTOS NACIONAIS               receita           1
1.1.04            PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS      reCeita           1
1.1.05            RECEITA DE ASSINATURAS                    REceita           1
1.1.06            RECEITA FINANCEIRA SOBRE APLICAÇÕES       receita           1
1.1.03            PRESTAÇÃO DE SERVIÇOS NACIONAIS           Receita           1
1.1.08            JUROS RECEBIDOS                           ReceitA           1
1.1.09            DIVIDENDOS RECEBIDOS                      receitA           1
1.1.10            RECEITA DE LICENCIAMENTO DE SOFTWARE      RECEita           1
3.1.01            SALÁRIOS E ORDENADOS                      despesa           1
3.1.02            ENCARGOS TRABALHISTAS                     DESPESA           1
3.1.03            IMPOSTOS E TAXAS                          Despesa           1
3.1.04            ALUGUEL E CONDOMÍNIO                      deSpesa           1
1.1.07            VARIAÇÃO CAMBIAL ATIVA                    RECEITA           1
3.1.05            ENERGIA ELÉTRICA                          DESpesa           1
3.1.07            INTERNET E TELECOMUNICAÇÕES               DESPESA           1
3.1.08            MARKETING E PUBLICIDADE                   DespESa           1
3.1.09            DESPESAS BANCÁRIAS INTERNACIONAIS         desPesA           1
3.1.10            TAXAS SOBRE OPERAÇÕES DE CÂMBIO           DESPesa           1
3.1.11            VARIAÇÃO CAMBIAL PASSIVA                  despESA           1
3.1.12            FRETES E LOGÍSTICA INTERNACIONAL          DESPESa           1
3.1.13            SOFTWARE / LICENÇA DE USO                 Despesa           1
3.1.14            CONSULTORIAS E SERVIÇOS TERCEIROS         dEspesa           1
3.1.15            SEGUROS EMPRESARIAIS                      DESpESA           1
3.1.16            MANUTENÇÃO DE SISTEMAS                    desPesa           1
3.1.17            INFRAESTRUTURA EM NUVEM                   DESPesa           1
3.1.18            CUSTOS COM API FINANCEIRA                 DespESa           1
3.1.19            TARIFAS DE TRANSFERÊNCIAS INTERNACIONAIS  despesa           1
3.1.20            PERDAS OPERACIONAIS                       DESPESA           1
3.1.21            OUTRAS DESPESAS OPERACIONAIS              despesa           1
Name: count, dtype: int64

In [172]:
df_cliente_bronze.head()

   id_cliente     nome_cliente    pais_cliente data_cadastro_cliente
0           1       Ana Souza           BRASIL            2023-01-05
1           2    CARLOS MENDES       portugal             12/01/2023
2           3   Julien  Martin         FranÃ§a            2023-01-18
3           4  michael johnson  Estados Unidos            25/01/2023
4           5     Sophia Brown         CANADÃ            2023-02-02

In [173]:
df_conta_pagamento_bronze.head()

,id_conta,descricao_conta,destino_pagamento_conta,codigo_categoria,observacao_conta,valor_conta,data_vencimento,data_pagamento,status_conta
0,1,Aquisição de hardware,Limpeza & Brilho,3.1.06,None,5051.54,2025-05-09,2025-05-13,Pago
1,2,Assinatura mensal,Limpeza & Brilho,3.1.10,Vencimento em feriado,1673.39,2025-03-15,2025-03-11,Pago
2,3,Manutenção preventiva,Logística Rápida Ltda,3.1.02,Desconto aplicado,4309.58,2025-08-29,None,Em aberto
3,4,Licenciamento anual,Gráfica Rápida Express,3.1.05,Parcela 1/3,5398.39,2025-06-14,2025-06-16,Pago
4,5,Manutenção preventiva,Restaurante Sabor & Arte,3.1.17,Aguardando nota fiscal,7268.57,2025-04-12,None,Em aberto

In [174]:
df_conta_receber_bronze.head()

,id_conta,descricao_conta,id_cliente,codigo_categoria,observacao_conta,valor_conta,data_vencimento,data_pagamento,status
0,1,Assinatura anual,73,1.1.05,Referente ao contrato Q4,39787.31,2025-09-27,2025-09-25,Pago
1,2,Recebimento de fatura,38,1.1.02,Aguardando transferência,216555.92,2025-05-12,None,Atrasado
2,3,Recebimento de fatura,52,1.1.06,Pagamento antecipado,8214.39,2025-04-17,2025-04-15,Pago
3,4,Recebimento de fatura,25,1.1.04,None,98459.91,2025-05-06,2025-05-02,Pago
4,5,Royalties,48,1.1.09,Bonificação incluída,236862.64,2025-01-20,None,Atrasado

In [175]:
print(df_cliente_bronze.info())
print(df_cliente_bronze.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cliente             75 non-null     int64
 1   nome_cliente           75 non-null     object
 2   pais_cliente           75 non-null     object
 3   data_cadastro_cliente  75 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.5+ KB
None
id_cliente  nome_cliente     pais_cliente    data_cadastro_cliente
1            Ana Souza       BRASIL          2023-01-05               1
2           CARLOS MENDES     portugal       12/01/2023               1
3           Julien  Martin   FranÃ§a         2023-01-18               1
4           michael johnson  Estados Unidos  25/01/2023               1
5            Sophia Brown    CANADÃ         2023-02-02               1
                                                                     ..
71          Amanda Ribeiro   BRASIL          2024-06-18               1
72          Francisco Neves   portugal       25/06/2024               1
73          Louis Mercier    FranÃ§a         2024-07-03               1
74          Daniel Brooks    ESTADOS UNIDOS  10/07/2024               1
75          Sarah Collins    CanadÃ¡         2024-07-18               1
Name: count, Length: 75, dtype: int64

In [176]:
display(df_meta_bronze)

            mes_meta  meta
0            01/2025  700k
1            02/2025  650k
2      março de 2025  750k
3            04/2025  750k
4            05/2025  750k
5            06/2025  700k
6            07/2025  650k
7          ago./2025  750k
8            09/2025  800k
9            10/2025  700k
10           11/2025  700k
11  dezembro de 2025  700k

In [177]:
df_meta_bronze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mes_meta  12 non-null     object
 1   meta      12 non-null     object
dtypes: object(2)
memory usage: 324.0+ bytes

In [178]:
df_banco_central_bronze.head()

  moeda        data  cotacao_compra  cotacao_venda        data_hora_cotacao
0   CAD  2024-01-02          3.6764         3.6780    2024-01-02 10:08:28.6
1   EUR  2024-01-02          5.3527         5.3553    2024-01-02 10:08:28.6
2   GBP  2024-01-02          6.1787         6.1814    2024-01-02 10:08:28.6
3   USD  2024-01-02          4.8874         4.8880    2024-01-02 10:08:28.6
4   CAD  2024-01-03          3.6940         3.6955  2024-01-03 10:13:43.439

In [179]:
df_meta_silver = pd.read_parquet('../data/silver/meta_2025_silver.parquet')
df_categoria_silver = pd.read_parquet('../data/silver/categoria_silver.parquet')
df_cliente_silver = pd.read_parquet('../data/silver/cliente_silver.parquet')

In [180]:
df_meta_silver.head()

  mes_ano_meta  meta_valor  mes   ano   nome_mes
0   2025-01-01    700000.0    1  2025    janeiro
1   2025-02-01    650000.0    2  2025  fevereiro
2   2025-03-01    750000.0    3  2025      marco
3   2025-04-01    750000.0    4  2025      abril
4   2025-05-01    750000.0    5  2025       maio

In [181]:
df_categoria_silver.head()

  codigo_categoria                        nome_categoria tipo_categoria
0           1.1.01           VENDA DE PRODUTOS NACIONAIS        RECEITA
1           1.1.02          VENDA DE PRODUTOS EXPORTACAO        RECEITA
2           1.1.03       PRESTACAO DE SERVICOS NACIONAIS        RECEITA
3           1.1.04  PRESTACAO DE SERVICOS INTERNACIONAIS        RECEITA
4           1.1.05                RECEITA DE ASSINATURAS        RECEITA

In [182]:
df_cliente_silver.head()

,id_cliente,nome_cliente,pais_cliente,moeda_pais,data_cadastro_cliente
0,1,Ana Souza,BRASIL,BRL,2023-01-05
1,2,Carlos Mendes,PORTUGAL,EUR,2023-01-12
2,3,Julien Martin,FRANCA,EUR,2023-01-18
3,4,Michael Johnson,ESTADOS UNIDOS,USD,2023-01-25
4,5,Sophia Brown,CANADA,CAD,2023-02-02

In [183]:
df_cliente_silver["pais_cliente"].value_counts()
# df_cliente_silver["moeda_pais"].value_counts()

pais_cliente
BRASIL            11
PORTUGAL          11
FRANCA            11
ESTADOS UNIDOS    11
CANADA            11
ARGENTINA         10
REINO UNIDO       10
Name: count, dtype: int64